export const PRODUCT={
  "ERROR_GET_PRODUCT":"ERROR_GET_PRODUCT",
  "LOADING_PRODUCT":"LOADING_PRODUCT",
  "SUCCESS_GET_PRODUCT":"SUCCESS_GET_PRODUCT"
};

export const PRODUCT_CATEGORIES={
  "VIDEO_GAMES":"VIDEO_GAMES",
  "MOVIES":"MOVIES",
  "ELECTRONICS":"ELECTRONICS"
};