export const PRODUCT={
  "ERROR_GET_PRODUCT":"ERROR_GET_PRODUCT",
  "LOADING_PRODUCT":"LOADING_PRODUCT",
  "SUCCESS_GET_PRODUCT":"SUCCESS_GET_PRODUCT",
  "SUCCESS_GET_NEXT_CATEGORY":"SUCCESS_GET_NEXT_CATEGORY",
  "SUCCESS_GET_PREV_CATEGORY":"SUCCESS_GET_PREV_CATEGORY"
};

export const CART={
  "ERROR_GET_CART":"ERROR_GET_CART",
  "LOADING_CART":"LOADING_CART",
  "SUCCESS_GET_CART":"SUCCESS_GET_CART",
  "ERROR_ADD_PRODUCT_CART":"ERROR_ADD_PRODUCT_CART",
  "LOADING_ADD_PRODUCT_CART":"LOADING_ADD_PRODUCT_CART",
  "SUCCESS_ADD_PRODUCT_CART":"SUCCESS_ADD_PRODUCT_CART",
  "ERROR_DELETE_PRODUCT_CART":"ERROR_DELETE_PRODUCT_CART",
  "LOADING_DELETE_PRODUCT_CART":"LOADING_DELETE_PRODUCT_CART",
  "SUCCESS_DELETE_PRODUCT_CART":"SUCCESS_DELETE_PRODUCT_CART",
  "ERROR_SEND_CART":"ERROR_SEND_CART",
  "LOADING_SEND_CART":"LOADING_SEND_CART",
  "SUCCESS_SEND_CART":"SUCCESS_SEND_CART",
  "SUCCESS_CLEAR_CART":"SUCCESS_CLEAR_CART"
};

export const PRODUCT_CATEGORIES={
  "ELECTRONICS":"ELECTRONICS",
  "MOVIES":"MOVIES",
  "VIDEO_GAMES":"VIDEO_GAMES"
};