export const PRODUCT={
  "ERROR_GET_PRODUCT":"ERROR_GET_PRODUCT",
  "LOADING_PRODUCT":"LOADING_PRODUCT",
  "SUCCESS_GET_PRODUCT":"SUCCESS_GET_PRODUCT"
};

export const CART={
  "ERROR_GET_CART":"ERROR_GET_CART",
  "LOADING_CART":"LOADING_CART",
  "SUCCESS_GET_CART":"SUCCESS_GET_CART",
  "ERROR_ADD_PRODUCT_CART":"ERROR_ADD_PRODUCT_CART",
  "LOADING_ADD_PRODUCT_CART":"LOADING_ADD_PRODUCT_CART",
  "SUCCESS_ADD_PRODUCT_CART":"SUCCESS_ADD_PRODUCT_CART",
  "ERROR_DELETE_PRODUCT_CART":"ERROR_DELETE_PRODUCT_CART",
  "LOADING_DELETE_PRODUCT_CART":"LOADING_DELETE_PRODUCT_CART",
  "SUCCESS_DELETE_PRODUCT_CART":"SUCCESS_DELETE_PRODUCT_CART"
};

export const PRODUCT_CATEGORIES={
  "VIDEO_GAMES":"VIDEO_GAMES",
  "MOVIES":"MOVIES",
  "ELECTRONICS":"ELECTRONICS"
};